Repository readmeio/rdme, pull requests merged in 2021-12, with the labels that each got.

#396 feat: swapping out the colors library for chalk
  .github/dependabot.yml
  __tests__/index.test.js
  bin/rdme
  package-lock.json
  package.json
  src/cmds/docs/index.js
  src/cmds/login.js
  src/cmds/open.js
  src/cmds/openapi.js
  src/cmds/swagger.js
  src/cmds/versions/index.js
  src/cmds/whoami.js
  src/index.js
  src/lib/help.js
Labels: dependencies

#378 feat: adding support for OpenAPI 3.1
  .github/workflows/ci.yml
  __tests__/__fixtures__/invalid-oas-3.1.json
  __tests__/__fixtures__/swagger.json
  __tests__/cmds/__snapshots__/openapi.test.js.snap
  __tests__/cmds/openapi.test.js
  package-lock.json
  package.json
  src/cmds/openapi.js
  src/cmds/swagger.js
Labels: enhancement

#397 feat: overhauling the help screen generator so it's consistent everywhere
  .github/dependabot.yml
  .github/workflows/ci.yml
  README.md
  __tests__/__snapshots__/index.test.js.snap
  __tests__/cmds/logout.test.js
  __tests__/index.test.js
  __tests__/lib/commands.test.js
  package-lock.json
  package.json
  src/cmds/logout.js
  src/cmds/oas.js
  src/cmds/swagger.js
  src/lib/commands.js
  src/lib/help.js
Labels: enhancement

#402 fix: upgrading oas and oas-normalize to fix an npm installation issue
  package-lock.json
  package.json
Labels: bug, dependencies

#404 feat(versions): stringify JSON for `--raw` option
  README.md
  __tests__/cmds/versions.test.js
  src/cmds/versions/index.js
Labels: enhancement

#406 docs: add/improve our command warnings
  __tests__/__snapshots__/index.test.js.snap
  __tests__/cmds/openapi.test.js
  __tests__/index.test.js
  src/cmds/openapi.js
  src/cmds/swagger.js
Labels: enhancement, documentation

#409 fix(openapi): return rejected `Promise` if spec uploads fail
  __tests__/cmds/openapi.test.js
  bin/rdme
  src/cmds/openapi.js
  src/index.js
Labels: bug

#410 refactor(open/openapi/validate): return promises, fix tests
  __tests__/cmds/open.test.js
  __tests__/cmds/openapi.test.js
  __tests__/cmds/validate.test.js
  src/cmds/open.js
  src/cmds/openapi.js
  src/cmds/validate.js
Labels: bug, enhancement
