Repository readmeio/rdme, pull requests merged in 2021-07, with the labels that each got.

#338 fix: change docs command to always update all valid docs
  __tests__/__fixtures__/failure-docs/fail-doc.md
  __tests__/__fixtures__/failure-docs/new-doc.md
  __tests__/cmds/docs.test.js
  src/cmds/docs/index.js
Labels: type:enhancement

#339 chore: running npm audit
  package-lock.json
Labels: scope:dependency, security

#313 Add --recursive option to doc sync command
  src/cmds/docs/index.js
Labels: type:enhancement

#340 fix: catch upload timeouts and return a better error message
  src/cmds/openapi.js
Labels: type:bug

#341 fix: command position sorting within the help screen
  src/lib/help.js
Labels: type:bug

#342 feat: add $ref bundling to OpenAPI/Swagger command
  __tests__/__fixtures__/ref-oas/external-components.json
  __tests__/__fixtures__/ref-oas/petstore.json
  __tests__/cmds/__snapshots__/openapi.test.js.snap
  __tests__/cmds/openapi.test.js
  src/cmds/openapi.js
Labels: type:enhancement

#343 feat: making the docs command recursive by default
  __tests__/.eslintrc
  __tests__/__fixtures__/existing-docs/subdir/another-doc.md
  __tests__/cmds/docs.test.js
  src/cmds/docs/index.js
Labels: type:enhancement
