Repository readmeio/rdme, pull requests merged in 2022-04, with the labels that each got.

#486 feat: throwing error messaging on node 12 being unsupported
  .github/workflows/ci.yml
  __tests__/bin.test.js
  __tests__/lib/getNodeVersion.test.js
  __tests__/lib/nodeVersionUtils.test.js
  bin/rdme
  src/lib/getNodeVersion.js
  src/lib/nodeVersionUtils.js
Labels: enhancement

#488 fix: our broken set-version-output script
  bin/set-version-output
  package.json
Labels: bug

#489 fix: messy issues with nodeVersionUtils helper needing semver installed
  __tests__/bin.test.js
  __tests__/lib/getNodeVersion.test.js
  __tests__/lib/isSupportedNodeVersion.test.js
  bin/rdme
  bin/set-version-output
  src/lib/getNodeVersion.js
  src/lib/isSupportedNodeVersion.js
  src/lib/nodeVersionUtils.js
Labels: enhancement

#490 feat: extending support to node 17
  .github/workflows/ci.yml
  package-lock.json
  package.json
Labels: enhancement

#491 docs(`docs`): clarify slug handling
  documentation/rdme.md
Labels: documentation

#492 fix: unsupported version error message having double "v"s
  __tests__/bin.test.js
  bin/rdme
Labels: bug

#493 feat(help): typos, add `rdme` version
  __tests__/__snapshots__/index.test.js.snap
  __tests__/bin.test.js
  __tests__/index.test.js
  src/index.js
  src/lib/help.js
Labels: enhancement

#495 feat: adding support for node 18
  .github/workflows/ci.yml
  __tests__/lib/isSupportedNodeVersion.test.js
  package-lock.json
  package.json
  src/lib/getNodeVersion.js
Labels: enhancement
