Repository readmeio/rdme, pull requests merged in 2022-09, with the labels that each got.

#596 chore(deps): bumping out of date deps
  package-lock.json
  package.json
Labels: dependencies

#577 feat(GHA): workflow file creation onboarding
  .github/workflows/retag-release.yaml
  __tests__/__snapshots__/index.test.ts.snap
  __tests__/cmds/__snapshots__/validate.test.ts.snap
  __tests__/cmds/docs/__snapshots__/index.test.ts.snap
  __tests__/cmds/docs/index.test.ts
  __tests__/cmds/openapi/__snapshots__/index.test.ts.snap
  __tests__/cmds/openapi/index.test.ts
  __tests__/cmds/openapi/reduce.test.ts
  __tests__/cmds/validate.test.ts
  __tests__/helpers/get-gha-setup.ts
  __tests__/helpers/get-git-mock.ts
  __tests__/helpers/github-workflow-schema.json
  __tests__/helpers/jest.matchers.ts
  __tests__/index.test.ts
  __tests__/lib/__snapshots__/createGHA.test.ts.snap
  __tests__/lib/createGHA.test.ts
  documentation/legacy-github-action.md
  documentation/rdme.md
  package-lock.json
  package.json
  src/.sink.d.ts
  src/cli.ts
  src/cmds/categories/create.ts
  src/cmds/categories/index.ts
  src/cmds/changelogs/index.ts
  src/cmds/changelogs/single.ts
  src/cmds/custompages/index.ts
  src/cmds/custompages/single.ts
  src/cmds/docs/edit.ts
  src/cmds/docs/index.ts
  src/cmds/docs/single.ts
  src/cmds/openapi/index.ts
  src/cmds/validate.ts
  src/cmds/versions/create.ts
  src/cmds/versions/delete.ts
  src/cmds/versions/index.ts
  src/cmds/versions/update.ts
  src/index.ts
  src/lib/baseCommand.ts
  src/lib/createGHA/baseFile.ts
  src/lib/createGHA/index.ts
  src/lib/decorators/supportsGHA.ts
  src/lib/fetch.ts
  src/lib/isCI.ts
  src/lib/isGitHub.ts
  src/lib/logger.ts
  src/lib/prepareOas.ts
  src/lib/versionSelect.ts
  tsconfig.json
Labels: enhancement, command:docs, command:openapi, command:categories

#597 feat: `npm init` alias
  packages/create/package.json
Labels: enhancement, command:openapi

#598 feat: migrate `validate` to `openapi:validate`
  .github/workflows/ci.yml
  .github/workflows/simple.yml
  CONTRIBUTING.md
  README.md
  __tests__/__snapshots__/index.test.ts.snap
  __tests__/cmds/openapi/__snapshots__/validate.test.ts.snap
  __tests__/cmds/openapi/validate.test.ts
  __tests__/lib/__snapshots__/commands.test.ts.snap
  __tests__/lib/__snapshots__/createGHA.test.ts.snap
  __tests__/lib/createGHA.test.ts
  src/cmds/index.ts
  src/cmds/openapi/reduce.ts
  src/cmds/openapi/validate.ts
  src/cmds/validate.ts
  src/lib/prepareOas.ts
Labels: enhancement, refactor, command:openapi

#599 fix(docs): don't use beta tag
  .github/workflows/docs.yml
  __tests__/helpers/get-gha-setup.ts
  __tests__/lib/createGHA.test.ts
  bin/set-version-output
  src/lib/createGHA/index.ts
  src/lib/getPkgVersion.ts
Labels: bug, refactor, documentation

#581 feat(docs): adds ability to delete docs from ReadMe if they're no longer in local folder
  README.md
  __tests__/__fixtures__/docs/delete-docs/some-doc.md
  __tests__/cmds/docs/index.test.ts
  src/cmds/docs/index.ts
  src/lib/deleteDoc.ts
  src/lib/fetch.ts
  src/lib/getDocs.ts
  src/lib/prompts.ts
  src/lib/pushDoc.ts
  src/lib/readDoc.ts
Labels: enhancement, command:docs

#603 feat(breaking/version): raw versions only, usage cleanup
  README.md
  __tests__/__snapshots__/index.test.ts.snap
  __tests__/cmds/logout.test.ts
  __tests__/cmds/open.test.ts
  __tests__/cmds/versions/index.test.ts
  __tests__/cmds/whoami.test.ts
  package-lock.json
  package.json
  src/cmds/versions/create.ts
  src/cmds/versions/delete.ts
  src/cmds/versions/index.ts
  src/cmds/versions/update.ts
  src/lib/baseCommand.ts
  src/lib/versionSelect.ts
Labels: enhancement, refactor, documentation, command:versions

#600 refactor(prompts): consolidate file path checks
  __tests__/index.test.ts
  __tests__/lib/checkFile.test.ts
  src/cmds/openapi/reduce.ts
  src/lib/checkFile.ts
  src/lib/createGHA/index.ts
Labels: refactor

#613 feat(openapi): raw command output option
  README.md
  __tests__/__snapshots__/index.test.ts.snap
  __tests__/cmds/openapi/index.test.ts
  src/cmds/openapi/index.ts
Labels: enhancement, command:openapi

#615 refactor(docs): internal command signatures
  src/lib/pushDoc.ts
  src/lib/readDoc.ts
Labels: refactor, command:docs

#616 fix(docs): use correct `_id` param
  __tests__/cmds/changelogs/index.test.ts
  __tests__/cmds/changelogs/single.test.ts
  __tests__/cmds/custompages/index.test.ts
  __tests__/cmds/custompages/single.test.ts
  __tests__/cmds/docs/index.test.ts
  __tests__/cmds/docs/single.test.ts
  src/lib/fetch.ts
  src/lib/pushDoc.ts
Labels: bug, command:docs

#611 test: minor test flakiness
  __tests__/helpers/get-gha-setup.ts
Labels: bug

#612 feat(openapi): add `--dryRun` option
  README.md
  __tests__/__snapshots__/index.test.ts.snap
  __tests__/cmds/openapi/index.test.ts
  src/cmds/openapi/index.ts
Labels: enhancement, command:openapi

#619 feat(breaking/login): remove `2fa` flag in favor of better prompts
  README.md
  __tests__/cmds/__snapshots__/login.test.ts.snap
  __tests__/cmds/login.test.ts
  src/cmds/login.ts
Labels: enhancement, command:other

#620 fix(bin): another `create` attempt
  .npmignore
  packages/create/bin/create.sh
  packages/create/package-lock.json
  packages/create/package.json
Labels: bug
