Repository readmeio/rdme, pull requests merged in 2022-11, with the labels that each got.

#658 chore(deps): bump a bunch of deps
  package-lock.json
  package.json
Labels: dependencies

#657 fix(gha-onboarding): don't run git commands in CI
  __tests__/lib/createGHA.test.ts
  src/lib/createGHA/index.ts
Labels: bug, type:ci

#659 fix: npm script awareness, TS fixes, test env refactors
  __tests__/cmds/categories/create.test.ts
  __tests__/cmds/categories/index.test.ts
  __tests__/cmds/changelogs/index.test.ts
  __tests__/cmds/changelogs/single.test.ts
  __tests__/cmds/custompages/index.test.ts
  __tests__/cmds/custompages/single.test.ts
  __tests__/cmds/docs/edit.test.ts
  __tests__/cmds/docs/index.test.ts
  __tests__/cmds/docs/prune.test.ts
  __tests__/cmds/docs/single.test.ts
  __tests__/cmds/openapi/index.test.ts
  __tests__/cmds/openapi/validate.test.ts
  __tests__/cmds/versions/create.test.ts
  __tests__/cmds/versions/delete.test.ts
  __tests__/cmds/versions/index.test.ts
  __tests__/cmds/versions/update.test.ts
  __tests__/helpers/get-gha-setup.ts
  __tests__/index.test.ts
  __tests__/lib/createGHA.test.ts
  __tests__/setup.js
  config/rdme-test.json
  package-lock.json
  package.json
  src/lib/createGHA/index.ts
  src/lib/isCI.ts
  src/lib/logger.ts
  src/lib/promptWrapper.ts
Labels: bug, enhancement, refactor, type:ci

#660 refactor(createGHA): drop hercule in favor of native solution
  package-lock.json
  package.json
  src/.sink.d.ts
  src/lib/createGHA/baseFile.ts
  src/lib/createGHA/index.ts
  tsconfig.json
Labels: dependencies, refactor

#666 fix: package.json keywords declarations
  package.json
Labels: documentation

#669 feat: adding support for uploading and validating Postman collections
  __tests__/__fixtures__/postman/petstore.collection.json
  __tests__/__fixtures__/postman/petstore.collection.yaml
  __tests__/cmds/openapi/index.test.ts
  package-lock.json
  package.json
  src/lib/prepareOas.ts
Labels: enhancement, command:openapi

#665 fix(createGHA): remove non-github remote check
  __tests__/lib/createGHA.test.ts
  src/lib/createGHA/index.ts
Labels: bug, GHA / CI

#672 fix: upgrade oas-normalize to fix a postman conversion issue
  package-lock.json
  package.json
Labels: bug

#667 fix: swap out `@npmcli/ci-detect` for `ci-info`
  __tests__/lib/fetch.test.ts
  package-lock.json
  package.json
  src/lib/isCI.ts
Labels: bug, dependencies

#674 ci: remove retag-release workflow
  .github/workflows/retag-release.yaml
  bin/retag-release.js
Labels: refactor

#671 feat(open): `rdme open` should have a flag for opening the dash
  __tests__/cmds/open.test.ts
  src/cmds/open.ts
  src/lib/versionSelect.ts
Labels: enhancement, command:other

#675 fix: don't prompt for version if only one exists
  __tests__/cmds/docs/index.test.ts
  __tests__/cmds/open.test.ts
  __tests__/cmds/openapi/index.test.ts
  src/lib/versionSelect.ts
Labels: enhancement, command:docs, command:openapi, command:versions, command:categories

#677 fix: unreachable code and those not getting flagged by eslint
  __tests__/cmds/open.test.ts
  package-lock.json
Labels: bug

#678 docs: update version/category to reflect new location
  .github/workflows/docs.yml
  documentation/github-actions-docs-example.md
  documentation/github-actions-openapi-example.md
  documentation/legacy-github-action.md
  documentation/rdme.md
Labels: documentation

#681 feat: proxy support
  .eslintrc
  CONTRIBUTING.md
  README.md
  __tests__/helpers/get-api-mock.ts
  __tests__/lib/fetch.test.ts
  src/lib/fetch.ts
  src/lib/getPkgVersion.ts
Labels: enhancement

#682 feat: major version tags
  .eslintrc
  .github/workflows/docs.yml
  MAINTAINERS.md
  README.md
  __tests__/cmds/docs/__snapshots__/index.test.ts.snap
  __tests__/cmds/openapi/__snapshots__/index.test.ts.snap
  __tests__/cmds/openapi/__snapshots__/validate.test.ts.snap
  __tests__/helpers/get-gha-setup.ts
  __tests__/lib/__snapshots__/createGHA.test.ts.snap
  __tests__/lib/createGHA.test.ts
  __tests__/lib/getNodeVersion.test.ts
  __tests__/lib/getPkgVersion.test.ts
  bin/set-major-version-tag.js
  bin/set-version-output
  bin/set-version-output.js
  documentation/github-actions-docs-example.md
  documentation/github-actions-openapi-example.md
  documentation/legacy-github-action.md
  documentation/rdme.md
  package.json
  src/lib/createGHA/index.ts
  src/lib/getNodeVersion.js
  src/lib/getPkgVersion.ts
  src/lib/logger.ts
Labels: enhancement, refactor

#684 feat(`openapi:reduce`): pass opts
  README.md
  __tests__/cmds/openapi/reduce.test.ts
  src/cmds/openapi/reduce.ts
Labels: enhancement, command:openapi
