Repository readmeio/rdme, pull requests merged in 2022-01, with the labels that each got.

#420 chore(deps): upgrading oas-related deps
  __tests__/cmds/__snapshots__/openapi.test.js.snap
  __tests__/cmds/__snapshots__/validate.test.js.snap
  package-lock.json
  package.json
Labels: dependencies

#421 fix(docs): directory sync fix + test bed rewrites
  __tests__/cmds/docs.test.js
  src/cmds/docs/edit.js
  src/cmds/docs/index.js
  src/lib/prompts.js
Labels: bug, refactor

#422 ci: tweak ESLint config, small refactors
  .eslintrc
  bin/rdme
Labels: refactor, documentation

#423 fix: quirks with version commands and config retrieval
  __tests__/__snapshots__/index.test.js.snap
  __tests__/cmds/__snapshots__/login.test.js.snap
  __tests__/cmds/__snapshots__/openapi.test.js.snap
  __tests__/cmds/__snapshots__/validate.test.js.snap
  __tests__/cmds/__snapshots__/versions.test.js.snap
  __tests__/cmds/__snapshots__/whoami.test.js.snap
  __tests__/cmds/docs.test.js
  __tests__/cmds/login.test.js
  __tests__/cmds/logout.test.js
  __tests__/cmds/open.test.js
  __tests__/cmds/openapi.test.js
  __tests__/cmds/versions.test.js
  __tests__/cmds/whoami.test.js
  __tests__/set-node-env.js
  src/cmds/docs/edit.js
  src/cmds/docs/index.js
  src/cmds/login.js
  src/cmds/logout.js
  src/cmds/open.js
  src/cmds/openapi.js
  src/cmds/versions/create.js
  src/cmds/versions/delete.js
  src/cmds/versions/index.js
  src/cmds/versions/update.js
  src/cmds/whoami.js
  src/index.js
  src/lib/help.js
  src/lib/versionSelect.js
Labels: bug

#426 chore(deps): bumping the oas parser to fix a bug with header validation
  package-lock.json
  package.json
Labels: bug, dependencies
