Repository readmeio/rdme, pull requests merged in 2022-03, with the labels that each got.

#439 docs: add GitHub Actions guidance
  .github/workflows/docs.yml
  README.md
  __tests__/lib/getNodeVersion.test.js
  bin/set-version-output
  documentation/rdme.md
  package.json
  src/lib/getNodeVersion.js
Labels: documentation

#452 docs: legacy GitHub Action docs
  documentation/legacy-github-action.md
Labels: documentation

#440 feat: dropping support for node 12
  .eslintrc
  .github/workflows/ci.yml
  bin/rdme
  package-lock.json
  package.json
  src/lib/apiError.js
  src/lib/prompts.js
Labels: enhancement, refactor

#454 feat(docs): add `--dryRun` option
  __tests__/cmds/docs.test.js
  src/cmds/docs/index.js
Labels: enhancement

#463 fix: a weirdly written promise
  src/cmds/openapi.js
Labels: refactor

#465 chore(deps): bump to setup-node v3 in action
  action.yml
Labels: dependencies

#451 chore: remove deprecated `token` parameter
  __tests__/cmds/openapi.test.js
  src/cmds/openapi.js
Labels: refactor

#466 fix(GHA): remove `chalk` overrides from error annotations
  action.yml
Labels: bug

#468 docs(GHA): small updates
  README.md
  documentation/legacy-github-action.md
  documentation/rdme.md
Labels: documentation

#471 fix(docs): github secrets usage
  documentation/rdme.md
Labels: documentation

#472 docs: remove duplicated community files
  .github/PULL_REQUEST_TEMPLATE.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  SECURITY.md
Labels: documentation

#477 chore(deps): bumping out of date deps
  .github/dependabot.yml
  package-lock.json
  package.json
Labels: dependencies

#479 docs(GHA): checkout guidance, workflow triggers
  README.md
  documentation/legacy-github-action.md
  documentation/rdme.md
Labels: documentation

#480 feat(openapi): specify spec path and type in success response
  __tests__/cmds/__snapshots__/validate.test.js.snap
  __tests__/cmds/openapi.test.js
  documentation/rdme.md
  src/cmds/openapi.js
  src/cmds/validate.js
  src/lib/prepareOas.js
Labels: enhancement

#485 chore(deps-dev): bumping out of date dev deps
  package-lock.json
  package.json
Labels: dependencies
