Repository readmeio/rdme, pull requests merged in 2022-07, with the labels that each got.

#529 feat: add `docs:single`
  README.md
  __tests__/cmds/docs.test.js
  src/cmds/docs/single.js
Labels: enhancement

#535 feat(config): add ability to override host + hub
  config/custom-environment-variables.json
  config/default.js
Labels: enhancement

#537 docs: add some language on `--2fa` option
  README.md
Labels: documentation

#538 feat: better error-handling for non-JSON responses
  __tests__/cmds/openapi.test.js
  package-lock.json
  package.json
  src/cmds/openapi.js
  src/lib/fetch.js
Labels: enhancement

#530 feat: add `categories` and `categories:create`
  README.md
  __tests__/cmds/categories.test.js
  src/cmds/categories/create.js
  src/cmds/categories/index.js
  src/cmds/docs/edit.js
  src/lib/commands.js
  src/lib/getCategories.js
Labels: enhancement

#540 refactor(docs): consolidate logic
  __tests__/cmds/docs.test.js
  src/cmds/docs/index.js
  src/cmds/docs/single.js
  src/lib/fetch.js
  src/lib/pushDoc.js
Labels: refactor

#542 refactor: split out fixtures, test cleanup
  __tests__/__fixtures__/docs/existing-docs/not-a-markdown-file
  __tests__/__fixtures__/docs/existing-docs/simple-doc.md
  __tests__/__fixtures__/docs/existing-docs/subdir/another-doc.md
  __tests__/__fixtures__/docs/failure-docs/fail-doc.md
  __tests__/__fixtures__/docs/failure-docs/new-doc.md
  __tests__/__fixtures__/docs/new-docs/new-doc.md
  __tests__/__fixtures__/docs/slug-docs/new-doc-slug.md
  __tests__/cmds/docs.test.js
  src/cmds/docs/index.js
  src/cmds/docs/single.js
  src/lib/pushDoc.js
Labels: refactor, command:docs

#543 feat: changelog endpoints
  README.md
  __tests__/__fixtures__/changelogs/existing-docs/not-a-markdown-file
  __tests__/__fixtures__/changelogs/existing-docs/simple-doc.md
  __tests__/__fixtures__/changelogs/existing-docs/subdir/another-doc.md
  __tests__/__fixtures__/changelogs/failure-docs/fail-doc.md
  __tests__/__fixtures__/changelogs/failure-docs/new-doc.md
  __tests__/__fixtures__/changelogs/new-docs/new-doc.md
  __tests__/__fixtures__/changelogs/slug-docs/new-doc-slug.md
  __tests__/cmds/changelogs.test.js
  src/cmds/changelogs/index.js
  src/cmds/changelogs/single.js
  src/lib/commands.js
Labels: enhancement, command:docs

#544 refactor: rename `category` to `cmdCategory` in `Command` class
  __tests__/lib/commands.test.js
  bin/rdme
  src/cmds/categories/create.js
  src/cmds/categories/index.js
  src/cmds/changelogs/index.js
  src/cmds/changelogs/single.js
  src/cmds/docs/edit.js
  src/cmds/docs/index.js
  src/cmds/docs/single.js
  src/cmds/login.js
  src/cmds/logout.js
  src/cmds/oas.js
  src/cmds/open.js
  src/cmds/openapi.js
  src/cmds/validate.js
  src/cmds/versions/create.js
  src/cmds/versions/delete.js
  src/cmds/versions/index.js
  src/cmds/versions/update.js
  src/cmds/whoami.js
  src/lib/commands.js
  src/lib/help.js
Labels: refactor

#545 feat: add retag-release workflow to add a vX.Y.Z tag for our GitHub Action
  .github/workflows/retag-release.yaml
  bin/retag-release.js
Labels: enhancement

#549 fix(docs/single): support files with `.markdown` extension
  __tests__/cmds/changelogs.test.js
  __tests__/cmds/custompages.test.js
  __tests__/cmds/docs.test.js
  src/cmds/changelogs/index.js
  src/cmds/changelogs/single.js
  src/cmds/custompages/index.js
  src/cmds/custompages/single.js
  src/cmds/docs/index.js
  src/cmds/docs/single.js
Labels: bug, command:docs

#550 refactor: DRY some docs logic
  .github/workflows/retag-release.yaml
  bin/retag-release.js
  src/cmds/changelogs/index.js
  src/cmds/custompages/index.js
  src/cmds/docs/index.js
  src/lib/pushDoc.js
Labels: refactor, command:docs

#548 docs: guidance on custompages + changelog
  documentation/rdme.md
Labels: documentation, command:docs
