Repository readmeio/rdme, pull requests merged in 2023-02, with the labels that each got.

#741 ci: fix code coverage in github actions
  jest.config.js
Labels: bug

#735 feat(GHA): add req header containing file URL
  .eslintrc
  __tests__/cmds/docs/index.test.ts
  __tests__/cmds/docs/single.test.ts
  __tests__/cmds/openapi/index.test.ts
  __tests__/helpers/get-gha-setup.ts
  __tests__/helpers/setup-gha-env.ts
  __tests__/lib/fetch.test.ts
  src/cmds/openapi/index.ts
  src/lib/fetch.ts
  src/lib/isCI.ts
  src/lib/prepareOas.ts
  src/lib/syncDocsPath.ts
Labels: enhancement, command:docs, command:openapi, API

#742 refactor(fetch): `readmeAPIFetch`, consolidate base URL
  __tests__/helpers/get-api-mock.ts
  __tests__/lib/fetch.test.ts
  src/cmds/categories/create.ts
  src/cmds/docs/edit.ts
  src/cmds/openapi/index.ts
  src/cmds/versions/create.ts
  src/cmds/versions/delete.ts
  src/cmds/versions/index.ts
  src/cmds/versions/update.ts
  src/lib/deleteDoc.ts
  src/lib/getCategories.ts
  src/lib/getDocs.ts
  src/lib/loginFlow.ts
  src/lib/prompts.ts
  src/lib/readmeAPIFetch.ts
  src/lib/streamSpecToRegistry.ts
  src/lib/syncDocsPath.ts
  src/lib/versionSelect.ts
Labels: refactor

#745 chore: run prettier on all files
  .prettierignore
  __tests__/__fixtures__/changelogs/existing-docs/simple-doc.md
  __tests__/__fixtures__/changelogs/existing-docs/subdir/another-doc.md
  __tests__/__fixtures__/custompages/existing-docs/simple-doc.md
  __tests__/__fixtures__/custompages/existing-docs/subdir/another-doc.md
  __tests__/__fixtures__/docs/delete-docs/some-doc.md
  __tests__/__fixtures__/docs/existing-docs/simple-doc.md
  __tests__/__fixtures__/docs/existing-docs/subdir/another-doc.md
  __tests__/__fixtures__/invalid-ref-oas/external-components.json
  __tests__/__fixtures__/invalid-swagger.json
  __tests__/__fixtures__/ref-oas/external-components.json
  __tests__/__fixtures__/relative-ref-oas/components/external-components.json
  __tests__/__fixtures__/swagger-with-invalid-extensions.json
  __tests__/__fixtures__/very-invalid-oas.json
  package.json
Labels: refactor

#760 chore: update JSON schema for github workflow files
  .eslintrc
  __tests__/helpers/github-workflow-schema.json
  bin/json-schema-store.js
  package.json
Labels: dependencies
