Repository readmeio/rdme, pull requests merged in 2023-11, with the labels that each got.

#936 chore(deps): upgrading `oas` and `oas-normalize`
  .eslintrc
  __tests__/lib/analyzeOas.test.ts
  package-lock.json
  package.json
  src/cmds/openapi/convert.ts
  src/cmds/openapi/inspect.ts
  src/cmds/openapi/reduce.ts
  src/lib/analyzeOas.ts
Labels: dependencies

#939 chore(deps): bump
  package-lock.json
  package.json
Labels: dependencies

#919 docs: update README with `v9` callout
  README.md
Labels: documentation

#922 chore: run type-checks on bin files
  bin/docker.js
  bin/json-schema-store.js
  bin/set-action-image.js
  bin/set-major-version-tag.js
  bin/set-version-output.js
Labels: enhancement

#941 feat(openapi/convert): support openapi in convert command
  __tests__/__snapshots__/index.test.ts.snap
  __tests__/cmds/openapi/convert.test.ts
  __tests__/lib/__snapshots__/commands.test.ts.snap
  __tests__/single-threaded/openapi/convert.test.ts
  src/cmds/openapi/convert.ts
Labels: enhancement, command:openapi
