Repository readmeio/rdme, pull requests merged in 2023-03, with the labels that each got.

#775 chore: bump deps
  .github/workflows/release.yml
  __tests__/helpers/github-workflow-schema.json
  package-lock.json
  package.json
Labels: dependencies

#776 fix: upgrading `oas-normalize` to move to our `postman-to-openapi` fork
  package-lock.json
Labels: bug, dependencies

#764 perf(docker): build executable
  Dockerfile
  package.json
Labels: performance

#779 fix(openapi): yaml strings would be improperly parsed as Date objects
  __tests__/helpers/github-workflow-schema.json
  package-lock.json
  package.json
Labels: bug, dependencies, command:openapi

#777 feat: container registry
  .github/workflows/ci.yml
  .github/workflows/docs.yml
  .github/workflows/release.yml
  .releaserc.yml
  Dockerfile
  action.yml
  bin/docker.js
  bin/set-action-image.js
  bin/verify-clis.sh
Labels: enhancement, GHA / CI

#782 chore(deps): bump
  .github/dependabot.yml
  __tests__/__snapshots__/index.test.ts.snap
  __tests__/cmds/openapi/__snapshots__/inspect.test.ts.snap
  package-lock.json
  package.json
Labels: dependencies

#781 feat: add GHA output with command result
  action.yml
  src/cli.ts
Labels: enhancement, GHA / CI

#784 fix(openapi): memory leak in large file handling within `oas-normalize`
  package-lock.json
  package.json
Labels: bug, command:openapi
