Repository readmeio/rdme, pull requests merged in 2023-05, with the labels that each got.

#811 chore(deps): bump
  .npmrc
  npm-shrinkwrap.json
Labels: enhancement, dependencies

#812 fix(openapi): postman responses without a response now get one
  npm-shrinkwrap.json
  package.json
Labels: bug, command:openapi

#815 fix: bump deps to handle `oas` bug
  npm-shrinkwrap.json
Labels: bug, dependencies
