Repository readmeio/rdme, pull requests merged in 2023-06, with the labels that each got.

#819 chore(deps): bump
  npm-shrinkwrap.json
Labels: dependencies

#818 fix(fetch): stricter source URL type-checking
  __tests__/lib/fetch.test.ts
  src/lib/readmeAPIFetch.ts
Labels: bug, command:docs, command:openapi

#820 chore(eslint): consistenly sorting on interface props
  __tests__/cmds/openapi/inspect.test.ts
  __tests__/lib/createGHA.test.ts
  npm-shrinkwrap.json
  package.json
  src/cmds/categories/create.ts
  src/cmds/login.ts
  src/cmds/open.ts
  src/cmds/openapi/convert.ts
  src/cmds/openapi/index.ts
  src/cmds/openapi/inspect.ts
  src/cmds/openapi/reduce.ts
  src/lib/analyzeOas.ts
  src/lib/apiError.ts
  src/lib/baseCommand.ts
  src/lib/commands.ts
  src/lib/getDocs.ts
  src/lib/help.ts
  src/lib/readmeAPIFetch.ts
Labels: enhancement

#824 fix(npm): revert shrinkwrap changes
  .prettierignore
  .releaserc.yml
  package-lock.json
Labels: bug
