Repository readmeio/rdme, pull requests merged in 2025-04, with the labels that each got.

#1206 chore(deps/v9): bump
  __tests__/helpers/github-workflow-schema.json
  package-lock.json
  package.json
Labels: dependencies

#1207 chore(deps): npm up
  package-lock.json
  package.json
Labels: dependencies

#1209 chore: refresh openapi definition
  src/lib/types/openapiDoc.ts
Labels: enhancement

#1211 refactor: git handler
  __tests__/commands/docs/index.test.ts
  __tests__/commands/docs/single.test.ts
  __tests__/commands/openapi/index.test.ts
  __tests__/commands/openapi/validate.test.ts
  __tests__/helpers/get-gha-setup.ts
  __tests__/helpers/get-git-mock.ts
  __tests__/helpers/git-mock.ts
  __tests__/helpers/oclif.ts
  __tests__/helpers/setup-gha-env.ts
  __tests__/lib/createGHA.test.ts
  __tests__/lib/fetch.test.ts
  src/lib/createGHA/index.ts
  src/lib/git.ts
  src/lib/readmeAPIFetch.ts
Labels: refactor

#1212 chore(deps): upgrading openapi-related tooling
  __tests__/commands/openapi/__snapshots__/inspect.test.ts.snap
  __tests__/helpers/github-workflow-schema.json
  package-lock.json
  package.json
Labels: dependencies, command:openapi, bug

#1214 docs: mark `docs upload` as an alpha
  README.md
  __tests__/commands/docs/__snapshots__/upload.test.ts.snap
  documentation/commands/docs.md
  src/commands/docs/upload.ts
Labels: documentation, command:docs

#1215 docs: whoops bring this doc back, but with a callout
  documentation/commands/docs.md
Labels: documentation, command:docs

#1213 feat(cli): add support for plugins
  package-lock.json
  package.json
  src/lib/hooks/createGHA.ts
Labels: enhancement

#1216 feat: various changes to get us plugin-ready
  __tests__/__fixtures__/docs/complex-frontmatter/basic.md
  __tests__/__fixtures__/docs/complex-frontmatter/link.md
  __tests__/commands/docs/__snapshots__/upload.test.ts.snap
  __tests__/commands/docs/upload.test.ts
  __tests__/helpers/oclif.ts
  __tests__/lib/frontmatter.test.ts
  bin/set-version-output.js
  knip.ts
  package-lock.json
  package.json
  src/commands/docs/upload.ts
  src/lib/frontmatter.ts
  src/lib/hooks/exported.ts
  src/lib/hooks/prerun.ts
  src/lib/readdirRecursive.ts
  src/lib/readmeAPIFetch.ts
  src/lib/syncPagePath.ts
  src/types.ts
  tsconfig.json
Labels: enhancement, refactor, command:docs, bug

#1217 feat: expose fetch utils
  knip.ts
  package.json
  src/lib/readmeAPIFetch.ts
  src/utils.ts
Labels: enhancement, plugins

#1218 fix: fetch util types
  src/lib/readmeAPIFetch.ts
Labels: bug, plugins

#1220 feat: add `docs migrate` command
  __tests__/commands/docs/__snapshots__/migrate.test.ts.snap
  __tests__/commands/docs/migrate.test.ts
  src/commands/docs/migrate.ts
  src/index.ts
  src/lib/readPage.ts
  src/lib/readmeAPIFetch.ts
  src/lib/syncDocsPath.legacy.ts
  src/lib/syncPagePath.ts
Labels: enhancement, command:docs, plugins

#1222 refactor: smol type enhancements
  src/lib/baseCommand.ts
  src/lib/readmeAPIFetch.ts
  src/types.ts
Labels: refactor

#1221 feat: minor tweaks to plugin extensibility
  src/lib/baseCommand.ts
  src/lib/readmeAPIFetch.ts
  src/lib/types/index.ts
  src/types.ts
  src/utils.ts
Labels: enhancement

#1224 fix(docs/upload): switch from `HEAD` to `GET` for initial page fetch
  __tests__/commands/docs/__snapshots__/upload.test.ts.snap
  __tests__/commands/docs/upload.test.ts
  src/lib/readmeAPIFetch.ts
  src/lib/syncPagePath.ts
Labels: command:docs, bug

#1225 feat: exposing types for creating API keys to plugins
  src/lib/types/index.ts
  src/types.ts
Labels: enhancement

#1226 feat(docs/migrate): add ability to unzip archives
  package-lock.json
  package.json
  src/commands/docs/migrate.ts
  src/lib/baseCommand.ts
  src/lib/hooks/exported.ts
  src/lib/readPage.ts
  src/lib/readmeAPIFetch.ts
  src/lib/types/index.ts
  src/lib/unzip.ts
  src/types.ts
Labels: enhancement, command:docs, plugins

#1227 fix: timeouts on `doc:upload`
  src/lib/readmeAPIFetch.ts
  src/lib/syncPagePath.ts
Labels: bug

#1230 feat(docs/migrate): migration stats
  __tests__/commands/docs/__snapshots__/upload.test.ts.snap
  __tests__/commands/docs/upload.test.ts
  src/commands/docs/migrate.ts
  src/commands/docs/upload.ts
  src/index.ts
  src/lib/hooks/exported.ts
  src/lib/syncPagePath.ts
  src/types.ts
Labels: enhancement, refactor, command:docs, plugins

#1233 refactor: consolidate doc frontmatter validation logic
  __tests__/lib/frontmatter.test.ts
  src/commands/docs/migrate.ts
  src/lib/frontmatter.ts
  src/lib/syncPagePath.ts
  src/lib/validateFrontmatter.ts
Labels: enhancement, refactor, command:docs, plugins

#1234 feat(docs): add ability to bypass autofix prompt
  __tests__/commands/docs/__snapshots__/upload.test.ts.snap
  __tests__/commands/docs/upload.test.ts
  src/commands/docs/migrate.ts
  src/commands/docs/upload.ts
  src/lib/flags.ts
  src/lib/validateFrontmatter.ts
Labels: enhancement, command:docs, plugins

#1235 chore: bump oclif deps/types + openapi
  package-lock.json
  src/commands/docs/migrate.ts
  src/lib/readdirRecursive.ts
  src/lib/types/openapiDoc.ts
Labels: dependencies, refactor

#1236 feat: better guides types, expose page stat type for `renderable` status
  __tests__/lib/apiError.test.ts
  src/lib/hooks/exported.ts
  src/lib/syncPagePath.ts
  src/lib/types/index.ts
  src/types.ts
Labels: enhancement, plugins

#1239 docs: improved flag sorting
  documentation/commands/changelogs.md
  documentation/commands/login.md
  documentation/commands/plugins.md
  src/commands/changelogs.ts
  src/commands/login.ts
  src/lib/help.ts
Labels: documentation, needs-backport-to-v9

#1238 fix: remove `/version` API deprecation warnings
  __tests__/__fixtures__/docs/existing-docs/subdir/another-doc.md
  __tests__/commands/docs/__snapshots__/upload.test.ts.snap
  __tests__/commands/docs/upload.test.ts
  __tests__/commands/openapi/__snapshots__/upload.test.ts.snap
  __tests__/commands/openapi/upload.test.ts
  __tests__/lib/frontmatter.test.ts
  documentation/commands/docs.md
  documentation/commands/openapi.md
  src/commands/docs/upload.ts
  src/commands/openapi/upload.ts
  src/index.ts
  src/lib/flags.ts
  src/lib/readmeAPIFetch.ts
  src/lib/syncPagePath.ts
  src/lib/types/index.ts
  src/lib/types/openapiDoc.ts
Labels: enhancement, documentation, command:docs, command:openapi, API, bug
