Repository readmeio/rdme, pull requests merged in 2025-02, with the labels that each got.

#1163 docs: warning callouts on outdated pages
  .github/workflows/docs.yml
  documentation/legacy/github-actions-docs-example.md
  documentation/legacy/github-actions-openapi-example.md
  documentation/legacy/legacy-github-action.md
  documentation/legacy/rdme.md
Labels: documentation

#1164 chore(deps/v9): bump
  __tests__/commands/docs/prune.test.ts
  __tests__/commands/openapi/index.test.ts
  package-lock.json
  package.json
  src/lib/readdirRecursive.ts
Labels: dependencies

#1165 chore(vscode): configure search exclusions
  .vscode/settings.json
Labels: refactor

#1156 fix(v9): point to correct dist-tag for outdated version notifications
  bin/dev.js
  bin/run.js
Labels: documentation, bug

#1161 docs: migration guide updates for `rdme docs upload`
  documentation/migration-guide.md
Labels: documentation

#1154 fix(openapi/upload): improved handling for YAML files
  __tests__/commands/openapi/__snapshots__/upload.test.ts.snap
  __tests__/commands/openapi/upload.test.ts
  package-lock.json
  package.json
  src/commands/openapi/upload.ts
Labels: command:openapi, bug

#1174 chore(deps-dev): upgrading our eslint standards
  __tests__/.eslintrc
  __tests__/bin.test.ts
  __tests__/commands/docs/upload.test.ts
  __tests__/commands/login.test.ts
  __tests__/commands/openapi/inspect.test.ts
  __tests__/commands/openapi/reduce.test.ts
  __tests__/commands/openapi/upload.test.ts
  __tests__/commands/openapi/validate.test.ts
  __tests__/lib/createGHA.test.ts
  __tests__/lib/fetch.test.ts
  __tests__/lib/getPkgVersion.test.ts
  __tests__/lib/validatePromptInput.test.ts
  package-lock.json
  package.json
Labels: dependencies

#1168 feat(openapi/upload): add `--confirm-overwrite` flag
  __tests__/commands/openapi/upload.test.ts
  src/commands/openapi/upload.ts
Labels: enhancement, command:openapi

#1172 ci: unify GHA build process
  .github/workflows/ci.yml
  package-lock.json
  package.json
  rollup.config.js
Labels: enhancement, refactor, GHA / CI

#1176 refactor: bring back json imports
  .gitignore
  CONTRIBUTING.md
  bin/dev.cmd
  package.json
  src/lib/configstore.ts
  src/lib/getPkg.ts
  vitest.config.ts
Labels: refactor, backport-to-v9
