Repository readmeio/rdme, pull requests merged in 2025-06, with the labels that each got.

#1257 feat: properly display file size feature in openapi inspect command
  __tests__/commands/openapi/__snapshots__/inspect.test.ts.snap
  __tests__/lib/__snapshots__/analyzeOas.test.ts.snap
  package-lock.json
  package.json
  src/commands/openapi/inspect.ts
Labels: enhancement

#1268 refactor: smol type improvement for reference pages
  src/lib/syncPagePath.ts
  src/lib/types/index.ts
Labels: enhancement, refactor

#1266 docs: migration intro edit
  documentation/migration-guide.md
Labels: documentation

#1270 chore: updating our OpenAPI definition
  src/lib/types/openapiDoc.ts
Labels: dependencies

#1273 chore: knip config cleanup
  knip.ts
Labels: refactor

#1276 chore(deps): updating out of date dependencies
  documentation/migration-guide.md
  package-lock.json
Labels: dependencies

#1272 feat: support for `rdme changelog upload`
  __tests__/__fixtures__/changelog/complex-frontmatter/basic.md
  __tests__/__fixtures__/changelog/complex-frontmatter/complex.md
  __tests__/__fixtures__/changelog/existing-docs/not-a-markdown-file
  __tests__/__fixtures__/changelog/existing-docs/simple-doc.md
  __tests__/__fixtures__/changelog/existing-docs/subdir/another-doc.md
  __tests__/__fixtures__/changelog/failure-docs/doc-sans-attributes.md
  __tests__/__fixtures__/changelog/failure-docs/new-doc.md
  __tests__/__fixtures__/changelog/legacy-docs/autofixable.md
  __tests__/__fixtures__/changelog/legacy-docs/unfixable.md
  __tests__/__fixtures__/changelog/mixed-docs/doc-sans-attributes.md
  __tests__/__fixtures__/changelog/mixed-docs/invalid-attributes.md
  __tests__/__fixtures__/changelog/mixed-docs/legacy-flag.md
  __tests__/__fixtures__/changelog/mixed-docs/new-doc-slug.mdx
  __tests__/__fixtures__/changelog/mixed-docs/not-a-markdown-file
  __tests__/__fixtures__/changelog/mixed-docs/simple-doc.md
  __tests__/__fixtures__/changelog/new-docs/new-doc.md
  __tests__/__fixtures__/changelog/slug-docs/new-doc-slug.md
  __tests__/commands/changelog/__snapshots__/upload.test.ts.snap
  __tests__/commands/changelog/upload.test.ts
  src/commands/changelog/upload.ts
  src/commands/changelogs.ts
  src/index.ts
  src/lib/hooks/exported.ts
  src/lib/readmeAPIFetch.ts
  src/lib/syncPagePath.ts
  src/lib/types/index.ts
  src/lib/validateFrontmatter.ts
  src/types.ts
  vitest.config.ts
Labels: enhancement, command:pages

#1264 refactor: route-specific frontmatter fixes
  __tests__/lib/__snapshots__/frontmatter.test.ts.snap
  __tests__/lib/frontmatter.test.ts
  src/lib/frontmatter.ts
Labels: enhancement, refactor, command:pages
