Repository readmeio/rdme, pull requests merged in 2025-08, with the labels that each got.

#1323 chore: bump deps, tsconfig updates, openapi updates
  package-lock.json
  package.json
  src/commands/openapi/resolve.ts
  src/commands/openapi/upload.ts
  src/index.ts
  src/lib/createGHA/index.ts
  src/lib/getPkg.ts
  src/lib/types/openapiDoc.ts
  src/utils.ts
  tsconfig.json
Labels: dependencies, needs-backport-to-v9

#1326 chore(deps-dev): upgrading biome and our standards package
  package-lock.json
  package.json
  src/commands/openapi/inspect.ts
  src/commands/openapi/resolve.ts
Labels: dependencies

#1329 chore(ci): lint script tweaks
  package.json
Labels: enhancement

#1333 fix(oclif): disable engine warning
  bin/run.js
Labels: bug, needs-backport-to-v9

#1332 fix(openapi/upload): unhide `--confirm-overwrite`
  documentation/commands/openapi.md
  src/commands/openapi/upload.ts
Labels: enhancement, documentation, command:openapi
